<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rolemap.xml</string>
		<string>catalog.xml</string>
	</array>
	<key>name</key>
	<string>Generic Setup</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml.strict</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.genericsetup</string>
	<key>uuid</key>
	<string>33B3749D-7213-4559-95E8-6409873D9988</string>
</dict>
</plist>
